apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 18.4.0
      helm:
        valueFiles:
          - $values/postgresql/values.yml
    - repoURL: https://github.com/iamenr0s/gitops-argocd.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/iamenr0s/gitops-argocd.git
      path: postgresql
      targetRevision: main
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true