apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-headers
  namespace: keycloak
spec:
  headers:
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      Content-Security-Policy: "frame-ancestors 'self'; frame-src 'self' data: blob:; default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:"
      Referrer-Policy: "no-referrer"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"

