---
global:
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  affinity: {}
  podLabels: {}
  podAnnotations: {}
  imagePullSecrets: []
  repository: ""
  compatibility:
    openshift:
      adaptSecurityContext: auto
replicaCount: 1
bitwarden-sdk-server:
  enabled: false
  namespaceOverride: ""
# -- Specifies the amount of historic ReplicaSets k8s should keep (see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy)
revisionHistoryLimit: 10
image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  tag: ""
  flavour: ""
installCRDs: false
crds:
  createClusterExternalSecret: false
  createClusterSecretStore: false
  createSecretStore: false
  createClusterGenerator: false
  createClusterPushSecret: false
  createPushSecret: false
  annotations: {}
  conversion:
    enabled: true
  unsafeServeV1Beta1: false
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
leaderElect: false
controllerClass: ""
extendedMetricLabels: false
scopedNamespace: ""
scopedRBAC: false
openshiftFinalizers: true
systemAuthDelegator: false
processClusterExternalSecret: true
processClusterPushSecret: true
processClusterStore: true
processSecretStore: true
processClusterGenerator: true
processPushSecret: true
genericTargets:
  enabled: false
  resources: []
createOperator: true
enableHTTP2: false
concurrent: 1
log:
  level: info
  timeEncoding: epoch
service:
  ipFamilyPolicy: ""
  ipFamilies: []
serviceAccount:
  create: true
  automount: true
  annotations: {}
  extraLabels: {}
  name: external-secrets
rbac:
  create: true
  servicebindings:
    create: true
  aggregateToView: true
  aggregateToEdit: true
extraEnv: []
extraArgs: {}
extraVolumes: []
extraObjects: []
extraVolumeMounts: []
extraInitContainers: []
extraContainers: []
deploymentAnnotations: {}
strategy: {}
podAnnotations: {}
podLabels: {}
podSecurityContext:
  enabled: true
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  enabled: true
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
resources: {}
serviceMonitor:
  enabled: false
  renderMode: skipIfMissing   # @schema enum: [skipIfMissing, failIfMissing, alwaysRender]
  namespace: ""
  additionalLabels: {}
  interval: 30s
  scrapeTimeout: 25s
  honorLabels: false
  metricRelabelings: []
  relabelings: []
metrics:
  listen:
    port: 8080
    secure:
      enabled: false
      certDir: /etc/tls
      certFile: /etc/tls/tls.crt
      keyFile: /etc/tls/tls.key
  service:
    enabled: false
    port: 8080
    annotations: {}
grafanaDashboard:
  enabled: false
  sidecarLabel: "grafana_dashboard"
  sidecarLabelValue: "1"
  annotations: {}
  extraLabels: {}
livenessProbe:
  enabled: false
  spec:
    address: ""
    port: 8082
    timeoutSeconds: 5
    failureThreshold: 5
    periodSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 10
    httpGet:
      port: live
      path: /healthz
nodeSelector: {}
tolerations: []
topologySpreadConstraints: []
affinity: {}
priorityClassName: ""
podDisruptionBudget:
  enabled: false
  minAvailable: 1    # @schema type:[integer, string]
  nameOverride: ""
hostNetwork: false
hostUsers:
webhook:
  annotations: {}
  create: true
  certCheckInterval: "5m"
  lookaheadInterval: ""
  replicaCount: 1
  log:
    level: info
    timeEncoding: epoch
  revisionHistoryLimit: 10
  certDir: /tmp/certs
  failurePolicy: Fail
  hostNetwork: false
  hostUsers:
  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    tag: ""
    flavour: ""
  imagePullSecrets: []
  port: 10250
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    extraLabels: {}
    name: ""
  nodeSelector: {}
  certManager:
    enabled: false
    addInjectorAnnotations: true
    cert:
      create: true
      issuerRef:
        group: cert-manager.io
        kind: "Issuer"
        name: "my-issuer"
      duration: "8760h0m0s"
      revisionHistoryLimit: 0
      renewBefore: ""
      privateKey: {}
      signatureAlgorithm: ""
      annotations: {}
  tolerations: []
  topologySpreadConstraints: []
  affinity: {}
  strategy: {}
  priorityClassName: ""
  podDisruptionBudget:
    enabled: false
    minAvailable: 1    # @schema type:[integer, string]
    nameOverride: ""
  metrics:
    listen:
      port: 8080
    service:
      enabled: false
      port: 8080
      annotations: {}
  readinessProbe:
    address: ""
    port: 8081
  extraEnv: []
  extraArgs: {}
  extraInitContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  secretAnnotations: {}
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    enabled: true
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  resources: {}
  service:
    enabled: true
    annotations: {}
    labels: {}
    type: ClusterIP
    loadBalancerIP: ""
certController:
  create: true
  requeueInterval: "5m"
  replicaCount: 1
  log:
    level: info
    timeEncoding: epoch
  revisionHistoryLimit: 10
  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    tag: ""
    flavour: ""
  imagePullSecrets: []
  rbac:
    create: true
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    extraLabels: {}
    name: ""
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  affinity: {}
  strategy: {}
  hostNetwork: false
  hostUsers:
  priorityClassName: ""
  podDisruptionBudget:
    enabled: false
    minAvailable: 1    # @schema type:[integer, string]
    nameOverride: ""
  metrics:
    listen:
      port: 8080
    service:
      enabled: false
      port: 8080
      annotations: {}
  readinessProbe:
    address: ""
    port: 8081
  startupProbe:
    enabled: false
    useReadinessProbePort: true
    port: ""
  extraEnv: []
  extraArgs: {}
  extraInitContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    enabled: true
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  resources: {}
dnsPolicy: ClusterFirst
dnsConfig: {}
podSpecExtra: {}
