apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kadalu
resources:
- https://gist.githubusercontent.com/iamenr0s/85ad999a3a500a7ec9921f53b76f91e0/raw/d1eedd67010e8d12eb988cfc3d7bfc83634b85a7/001-kadalu-operator.yml
- kadalu-storage-generator.yml
