apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://infra.tekton.dev/tekton-releases/pipeline/latest/release.yaml
patchesStrategicMerge:
  - patches/delete-validatingwebhook-config.yml
  - patches/delete-validatingwebhook-validation.yml

