apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.influxdata.com/
      chart: influxdb2
      targetRevision: 2.1.2
      helm:
        valueFiles:
          - $values/influxdb/values.yml
    - repoURL: https://github.com/iamenr0s/gitops-argocd.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/iamenr0s/gitops-argocd.git
      path: influxdb
      targetRevision: main
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: influxdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
