apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - acme-contact.externalsecret.yml
  - cloudflare-api-token.externalsecret.yml
  - cluster-issuer-letsencrypt-staging.yml
  - cluster-issuer-letsencrypt-production.yml
